/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pawuwa (https://sketchfab.com/pawuwa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/technology-console-c2ed8d4fb9dd4d8186a22ff2399ec171
Title: Technology console
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import {a} from '@react-spring/three'

import radioScene from '../assets/3D/technology_console.glb'

const Radio = (props) => {
  const { nodes, materials } = useGLTF(radioScene)
  const radioRef = useRef()
  return (
    <a.group ref={radioRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            
            
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Material}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </a.group>
  )
}

export default Radio 